# chtc-checkm.sub
#
#
# Specify the HTCondor Universe
universe = docker
docker_image = sstevens/checkm:latest

log = chtc-checkm_$(Cluster).log
error = chtc-checkm_$(Cluster)_$(Process).err
requirements = (OpSysMajorVer == 7)
#
# Specify your executable, arguments, and a file for HTCondor to store standard
#  output.
executable = chtc-checkm.sh
arguments = $(bin)
output = chtc-checkm_$(Cluster).out
#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = refs/$(bin)
#transfer_output_files = $(bin)-checkm.txt
#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.

request_cpus = 1
request_memory = 40GB
request_disk = 12GB
#
# Tell HTCondor to run every fastq file in the provided list:
queue bin from bins_to_classify.txt

